Review advanced
C2SM/git-course pull request #118
Opened 2024-09-11 13:16 UTC by AnnikaLau

2024-09-16 20:24 UTC, mjaehn requested changes
Dear @AnnikaLau, fantastic work on the revision of the 2024 advanced course! Especially the overall formatting and the overhaul of the _worktree_ section. 

There are just a few minor comments regarding language and consistency. Otherwise, this is ready to be merged. 👍🏻

2024-09-16 20:24 UTC, mjaehn commented on advanced/Exercise_3_gitignore.md
>  * [Generate the README file in HTML](#html)
Please check for consistency for the whole exercise: README vs _README_

2024-09-16 20:24 UTC, mjaehn commented on advanced/Exercise_5_git-rebase.md
> +To visualise the difference, take a look at the Git log graph (remember what we learned in [Exercise 1](./Exercise_1_git-log-diff-show.md#use-git-log-to-have-a-look-at-the-repository))
I think we use American English (visuali**z**e) for most of the rest. Can be considered as another consistency check.

2024-09-16 20:24 UTC, mjaehn commented on advanced/Exercise_8_git-submodule.md
> +Once you have done this, navigate back into into root of the *conference_planning* folder and use `git submodule update` to get the main repository to fetch the new commit from the *posters* reposito
```suggestion
Once you have done this, navigate back to the root of the *conference_planning* folder and use `git submodule update` to get the main repository to fetch the new commit from the *posters* repository.
```

2024-09-17 08:02 UTC, AnnikaLau commented
> Dear @AnnikaLau, fantastic work on the revision of the 2024 advanced course! Especially the overall formatting and the overhaul of the _worktree_ section.
> 
> There are just a few minor comments regarding language and consistency. Otherwise, this is ready to be merged. 👍🏻

Thank you @mjaehn for your fantastic review! I implemented all your requested changes.

2024-09-17 08:06 UTC, mjaehn approved these changes
LPTM!

2024-09-17 08:07 UTC, merged